#!/bin/bash
# Usage ./run src/minstack.c

# Check if the source file is passed as an argument
if [ $# -lt 1 ]; then
    echo "Usage: $0 source_file.cpp"
    exit 1
fi

# Set the source file as the argument
SRC="$1"

# Update the timestamp of the source file to force make to recompile
touch "$SRC"

# Run make and then execute the output
make SRC="$SRC" && ./leetcode.out
